_BASE_: "../Base-Strongerbaseline.yml"



MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: "18x"
  HEADS:
    IN_FEAT: 512

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/market1501/sbs_R18"
